apiVersion: v2
name: castai-autoscaler
description: A Helm chart for Kubernetes

# This chart is an 'application' type.
type: application

# Bump this version each time you change the chart.
version: 0.1.0

# The version of your application being deployed.
appVersion: "1.16.0"

# Remove or comment out any "sources" block referencing @castai-helm.
# Instead, reference the real URL for each dependency below.

dependencies:
  - name: castai-cluster-controller
    version: 0.80.2
    repository: "https://castai.github.io/helm-charts"
    condition: castai-cluster-controller.enabled

  - name: castai-evictor
    version: 0.31.49
    repository: "https://castai.github.io/helm-charts"
    condition: castai-evictor.enabled

  - name: castai-pod-mutator
    version: 0.0.15
    repository: "https://castai.github.io/helm-charts"
    condition: castai-pod-mutator.enabled

  - name: castai-pod-pinner
    version: 1.2.0
    repository: "https://castai.github.io/helm-charts"
    condition: castai-pod-pinner.enabled

  - name: castai-spot-handler
    version: 0.26.0
    repository: "https://castai.github.io/helm-charts"
    condition: castai-spot-handler.enabled

  - name: egressd
    version: 0.1.42
    repository: "https://castai.github.io/helm-charts"
    condition: egressd.enabled

  - name: gpu-metrics-exporter
    version: 0.1.18
    repository: "https://castai.github.io/helm-charts"
    condition: gpu-metrics-exporter.enabled
