apiVersion: v2
name: castai-autoscaler
description: A Helm chart for Kubernetes

# Chart type: 'application' or 'library'. Here, we want 'application'.
type: application

# Increment this whenever you make changes to the chart.
version: 0.1.0

# The version of the application being deployed.
appVersion: "1.16.0"

# If you're using the official CAST AI Helm repo, add it as a source.
sources:
  - https://castai.github.io/helm-charts

# Dependencies for all CAST AI components.
dependencies:
  - condition: castai-cluster-controller.enabled
    name: castai-cluster-controller
    repository: "@castai-helm"
    version: 0.80.2

  - condition: castai-evictor.enabled
    name: castai-evictor
    repository: "@castai-helm"
    version: 0.31.49

  - condition: castai-pod-mutator.enabled
    name: castai-pod-mutator
    repository: "@castai-helm"
    version: 0.0.15

  - condition: castai-pod-pinner.enabled
    name: castai-pod-pinner
    repository: "@castai-helm"
    version: 1.2.0

  - condition: castai-spot-handler.enabled
    name: castai-spot-handler
    repository: "@castai-helm"
    version: 0.26.0

  - condition: egressd.enabled
    name: egressd
    repository: "@castai-helm"
    version: 0.1.42

  - condition: gpu-metrics-exporter.enabled
    name: gpu-metrics-exporter
    repository: "@castai-helm"
    version: 0.1.18

